<?php
/**
 * Created by PhpStorm.
 * User: yourh
 * Date: 2017/8/13
 * Time: 11:48
// */
namespace backend\controllers;

class AuthController extends \yii\web\Controller{

    //控制器初始化
//    public function init()
//    {
//        if(\Yii::$app->user->isGuest){
//            $this->redirect('login');
//            return parent::init();
//        }
//    }

//    public function behaviors()
//    {
//        if (\Yii::$app->user->isGuest){
//            return \Yii::$app->user->loginUrl;
//        }
//        return parent::behaviors(); // TODO: Change the autogenerated stub
//    }
}